language: c
os: osx

before_install:
  - brew install gcc
  - brew link --overwrite gcc

script:
  - gfortran -O0 main.f90 -o main

  - ./hello

after_success:
  - bash <(curl -s https://codecov.io/bash)
