language: c
os: osx

before_install:
  - rm '/usr/local/include/c++'
  - brew install gcc

script:
  - gfortran -O0 main.f90 -o main

  - ./main

after_success:
  - bash <(curl -s https://codecov.io/bash)
